GET https://localhost:3000
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IkphY2sgQmxhY2siLCJlbWFpbCI6ImpiQGdtYWlsLmNvbSIsImlhdCI6MTU5OTQ5MTc4N30.ZUBfYqdDldlUfHsrvq1QBmaDYYQuCiU4bX3xzqQBrcmtcUc-NxrMh2tfUXpIEMQ8MqAE6Mev9a6RrZa25dobnA

###

POST https://localhost:3000/login
Content-Type: application/json

{
    "email": "jb@gmail.com",
    "password": "password"
}

###

GET https://localhost:3000/listPatients
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MCwibmFtZSI6IkphY2sgQmxhY2siLCJlbWFpbCI6ImpiQGdtYWlsLmNvbSIsImlhdCI6MTU5OTQ5MTc4N30.ZUBfYqdDldlUfHsrvq1QBmaDYYQuCiU4bX3xzqQBrcmtcUc-NxrMh2tfUXpIEMQ8MqAE6Mev9a6RrZa25dobnA